package dnm.student_management.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dnm.student_management.controller.DataController;
import dnm.student_management.controller.DataControllerImp;
import dnm.student_management.model.Course;
import dnm.student_management.model.Registering;
import dnm.student_management.model.Student;
import dnm.student_management.model.Subject;
import java.text.ParseException;
import java.util.Date;

public class HomeFrm extends javax.swing.JFrame implements ActionListener {

    private List<Subject> subjects;
    private List<Student> students;
    private List<Registering> registerings;
    private List<Course> courses;

    private DefaultTableModel tableModelSubject;
    private DefaultTableModel tableModelStudent;
    private DefaultTableModel tableModelRegistering;
    private DefaultTableModel tableModelCourse;
    private DataController dataController;
    private SimpleDateFormat simpleDateFormat;

    private int selectedIndex;

    /**
     * Creates new form HomeFrm
     */
    public HomeFrm() {
        initComponents();
        setLocationRelativeTo(null);
        addButtonGroup();
        addActionListener();
        subjects = new ArrayList<>();
        tableModelSubject = (DefaultTableModel) tblSubject.getModel();
        tableModelStudent = (DefaultTableModel) tblStudent.getModel();
        tableModelRegistering = (DefaultTableModel) tblRegistering.getModel();
        tableModelCourse = (DefaultTableModel) tblCourse.getModel();
        dataController = new DataControllerImp();
        simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        selectedIndex = -1;
        loadData();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSortSubject = new javax.swing.ButtonGroup();
        buttonGroupSearchSubject = new javax.swing.ButtonGroup();
        buttonGroupSearchStudent = new javax.swing.ButtonGroup();
        buttonGroupSortStudent = new javax.swing.ButtonGroup();
        buttonGroupSearchRegistering = new javax.swing.ButtonGroup();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rbSortSubjectNameASC = new javax.swing.JRadioButton();
        rbSortSubjectNameDESC = new javax.swing.JRadioButton();
        rbSortSubjectLessonASC = new javax.swing.JRadioButton();
        rbSortSubjectLessonDESC = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        rbSearchSubjectByName = new javax.swing.JRadioButton();
        rbSearchSubjectByNumOfLesson = new javax.swing.JRadioButton();
        txtSearchSubjectByName = new javax.swing.JTextField();
        btnSearchSubject = new javax.swing.JButton();
        txtSearchSubjectLessonFrom = new javax.swing.JTextField();
        txtSearchSubjectLessonTo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubject = new javax.swing.JTable();
        btnRefreshSubject = new javax.swing.JButton();
        btnAddNewSubject = new javax.swing.JButton();
        btnEditSubject = new javax.swing.JButton();
        btnRemoveSubject = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        rbSortStudentNameASC = new javax.swing.JRadioButton();
        rbSortStudentNameDESC = new javax.swing.JRadioButton();
        rbSortStudentIdASC = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        rbSearchStudentByName = new javax.swing.JRadioButton();
        rbSearchStudentId = new javax.swing.JRadioButton();
        txtSearchStudentName = new javax.swing.JTextField();
        btnSearchStudent = new javax.swing.JButton();
        txtSearchStudentById = new javax.swing.JTextField();
        rbSearchStudentByMajor = new javax.swing.JRadioButton();
        comboMajor = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnRefreshStudent = new javax.swing.JButton();
        btnAddNewStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        btnRemoveStudent = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnRefreshRegistering = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRegistering = new javax.swing.JTable();
        btnAddNewRegistering = new javax.swing.JButton();
        btnRemoveRegistering = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        rbSearchReByStudentName = new javax.swing.JRadioButton();
        rbSearchReByRegisterTime = new javax.swing.JRadioButton();
        txtSearchReByStudentName = new javax.swing.JTextField();
        btnSearchRegistering = new javax.swing.JButton();
        txtSearchReByRegisterTimeFrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboSortRegistering = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSearchReByRegisterTimeTo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        btnCreateCourse = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ ĐĂNG KÝ MÔN HỌC");
        setResizable(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sort subject list", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        rbSortSubjectNameASC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSortSubjectNameASC.setText("By name a-z");

        rbSortSubjectNameDESC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSortSubjectNameDESC.setText("By name z-a");

        rbSortSubjectLessonASC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSortSubjectLessonASC.setText("By ascending number of sections");

        rbSortSubjectLessonDESC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSortSubjectLessonDESC.setText("By descending number of sections");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSortSubjectNameASC)
                    .addComponent(rbSortSubjectNameDESC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSortSubjectLessonDESC)
                    .addComponent(rbSortSubjectLessonASC))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSortSubjectNameASC)
                    .addComponent(rbSortSubjectLessonASC))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSortSubjectNameDESC)
                    .addComponent(rbSortSubjectLessonDESC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search for subjects", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        rbSearchSubjectByName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSearchSubjectByName.setText("By name");

        rbSearchSubjectByNumOfLesson.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSearchSubjectByNumOfLesson.setText("By number of lessons");

        txtSearchSubjectByName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSearchSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchSubject.setText("Find");

        txtSearchSubjectLessonFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSearchSubjectLessonTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("To");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("From:  ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbSearchSubjectByNumOfLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSearchSubjectByName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSearchSubjectByName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchSubjectLessonFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearchSubjectLessonTo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSearchSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSearchSubjectByName)
                            .addComponent(txtSearchSubjectByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSearchSubjectByNumOfLesson)
                            .addComponent(txtSearchSubjectLessonFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchSubjectLessonTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnSearchSubject)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tblSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID", "Subject name", "Number of lessons", "Subject type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubject);

        btnRefreshSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRefreshSubject.setText("Refresh");
        btnRefreshSubject.setName(""); // NOI18N

        btnAddNewSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddNewSubject.setText("Add");

        btnEditSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditSubject.setText("Edit");

        btnRemoveSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoveSubject.setText("Delete");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnRefreshSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnAddNewSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnEditSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnRemoveSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshSubject)
                    .addComponent(btnAddNewSubject)
                    .addComponent(btnEditSubject)
                    .addComponent(btnRemoveSubject))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("SUBJECT MANAGEMENT", jPanel1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sort student list", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        rbSortStudentNameASC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSortStudentNameASC.setText("By name a-z");

        rbSortStudentNameDESC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSortStudentNameDESC.setText("By name z-a");

        rbSortStudentIdASC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSortStudentIdASC.setText("By student ID a-z");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(rbSortStudentNameASC)
                        .addGap(75, 75, 75)
                        .addComponent(rbSortStudentIdASC))
                    .addComponent(rbSortStudentNameDESC))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSortStudentNameASC)
                    .addComponent(rbSortStudentIdASC))
                .addGap(18, 18, 18)
                .addComponent(rbSortStudentNameDESC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search for students", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        rbSearchStudentByName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSearchStudentByName.setText("By name");

        rbSearchStudentId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSearchStudentId.setText("By student ID");

        txtSearchStudentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSearchStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchStudent.setText("Find");

        txtSearchStudentById.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rbSearchStudentByMajor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSearchStudentByMajor.setText("By major");

        comboMajor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboMajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Information Technology", "Electronics", "Telecommunications", "Business Administration", "Data Science" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rbSearchStudentId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbSearchStudentByName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rbSearchStudentByMajor))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(comboMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearchStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtSearchStudentById))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSearchStudentByName)
                    .addComponent(txtSearchStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSearchStudentId)
                    .addComponent(txtSearchStudentById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSearchStudentByMajor)
                    .addComponent(comboMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Full name", "Date of birth", "Address", "Email", "Phone number", "Class", "Major", "School year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblStudent);
        if (tblStudent.getColumnModel().getColumnCount() > 0) {
            tblStudent.getColumnModel().getColumn(4).setResizable(false);
            tblStudent.getColumnModel().getColumn(5).setResizable(false);
        }

        btnRefreshStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRefreshStudent.setText("Refresh");
        btnRefreshStudent.setName(""); // NOI18N

        btnAddNewStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddNewStudent.setText("Add");

        btnEditStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditStudent.setText("Edit");

        btnRemoveStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoveStudent.setText("Delete");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnRefreshStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnAddNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnRemoveStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshStudent)
                    .addComponent(btnAddNewStudent)
                    .addComponent(btnEditStudent)
                    .addComponent(btnRemoveStudent))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("STUDENT MANAGEMENT", jPanel2);

        btnRefreshRegistering.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRefreshRegistering.setText("Refresh");
        btnRefreshRegistering.setName(""); // NOI18N

        tblRegistering.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblRegistering.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Full name", "Class", "Subject ID", "Subject name", "Registration time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblRegistering);

        btnAddNewRegistering.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddNewRegistering.setText("Add");

        btnRemoveRegistering.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoveRegistering.setText("Delete");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search and sort registration tables", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        buttonGroupSearchRegistering.add(rbSearchReByStudentName);
        rbSearchReByStudentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSearchReByStudentName.setText("Search by student name");

        buttonGroupSearchRegistering.add(rbSearchReByRegisterTime);
        rbSearchReByRegisterTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSearchReByRegisterTime.setText("Search by registration time");

        txtSearchReByStudentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSearchRegistering.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchRegistering.setText("Find");

        txtSearchReByRegisterTimeFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sort by:");

        comboSortRegistering.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboSortRegistering.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending Name a-z", "Descending Name z-a", "Early-Late Registration Time", "Late-Early Registration Time" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Enter student name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("From date:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("To date:");

        txtSearchReByRegisterTimeTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSearchReByStudentName)
                            .addComponent(rbSearchReByRegisterTime))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearchReByRegisterTimeTo, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(txtSearchReByRegisterTimeFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(txtSearchReByStudentName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(45, 45, 45)
                        .addComponent(btnSearchRegistering, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1032, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(comboSortRegistering, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboSortRegistering, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSearchReByStudentName)
                    .addComponent(txtSearchReByStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSearchReByRegisterTime)
                    .addComponent(txtSearchReByRegisterTimeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchRegistering)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSearchReByRegisterTimeTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnRefreshRegistering, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(btnAddNewRegistering, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(btnRemoveRegistering, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(589, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveRegistering)
                    .addComponent(btnAddNewRegistering)
                    .addComponent(btnRefreshRegistering))
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addGap(61, 61, 61)))
        );

        jTabbedPane1.addTab("REGISTRATION MANAGEMENT", jPanel3);

        tblCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course section", "Student ID", "Full name", "Class", "Subject ID", "Subject name", "Registration time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblCourse);

        btnCreateCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCreateCourse.setText("Create a course section");
        btnCreateCourse.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(btnCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(474, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateCourse)
                .addContainerGap(603, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("CLASS DIVISION", jPanel4);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/turn-off-24px.png"))); // NOI18N
        jMenuItem1.setText("Thoát");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewRegistering;
    private javax.swing.JButton btnAddNewStudent;
    private javax.swing.JButton btnAddNewSubject;
    private javax.swing.JButton btnCreateCourse;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnEditSubject;
    private javax.swing.JButton btnRefreshRegistering;
    private javax.swing.JButton btnRefreshStudent;
    private javax.swing.JButton btnRefreshSubject;
    private javax.swing.JButton btnRemoveRegistering;
    private javax.swing.JButton btnRemoveStudent;
    private javax.swing.JButton btnRemoveSubject;
    private javax.swing.JButton btnSearchRegistering;
    private javax.swing.JButton btnSearchStudent;
    private javax.swing.JButton btnSearchSubject;
    private javax.swing.ButtonGroup buttonGroupSearchRegistering;
    private javax.swing.ButtonGroup buttonGroupSearchStudent;
    private javax.swing.ButtonGroup buttonGroupSearchSubject;
    private javax.swing.ButtonGroup buttonGroupSortStudent;
    private javax.swing.ButtonGroup buttonGroupSortSubject;
    private javax.swing.JComboBox<String> comboMajor;
    private javax.swing.JComboBox<String> comboSortRegistering;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbSearchReByRegisterTime;
    private javax.swing.JRadioButton rbSearchReByStudentName;
    private javax.swing.JRadioButton rbSearchStudentByMajor;
    private javax.swing.JRadioButton rbSearchStudentByName;
    private javax.swing.JRadioButton rbSearchStudentId;
    private javax.swing.JRadioButton rbSearchSubjectByName;
    private javax.swing.JRadioButton rbSearchSubjectByNumOfLesson;
    private javax.swing.JRadioButton rbSortStudentIdASC;
    private javax.swing.JRadioButton rbSortStudentNameASC;
    private javax.swing.JRadioButton rbSortStudentNameDESC;
    private javax.swing.JRadioButton rbSortSubjectLessonASC;
    private javax.swing.JRadioButton rbSortSubjectLessonDESC;
    private javax.swing.JRadioButton rbSortSubjectNameASC;
    private javax.swing.JRadioButton rbSortSubjectNameDESC;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTable tblRegistering;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTable tblSubject;
    private javax.swing.JTextField txtSearchReByRegisterTimeFrom;
    private javax.swing.JTextField txtSearchReByRegisterTimeTo;
    private javax.swing.JTextField txtSearchReByStudentName;
    private javax.swing.JTextField txtSearchStudentById;
    private javax.swing.JTextField txtSearchStudentName;
    private javax.swing.JTextField txtSearchSubjectByName;
    private javax.swing.JTextField txtSearchSubjectLessonFrom;
    private javax.swing.JTextField txtSearchSubjectLessonTo;
    // End of variables declaration//GEN-END:variables

    private void addButtonGroup() {
        buttonGroupSearchSubject.add(rbSearchSubjectByName);
        buttonGroupSearchSubject.add(rbSearchSubjectByNumOfLesson);

        buttonGroupSortSubject.add(rbSortSubjectLessonASC);
        buttonGroupSortSubject.add(rbSortSubjectLessonDESC);
        buttonGroupSortSubject.add(rbSortSubjectNameASC);
        buttonGroupSortSubject.add(rbSortSubjectNameDESC);

        buttonGroupSearchStudent.add(rbSearchStudentId);
        buttonGroupSearchStudent.add(rbSearchStudentByMajor);
        buttonGroupSearchStudent.add(rbSearchStudentByName);

        buttonGroupSortStudent.add(rbSortStudentIdASC);
        buttonGroupSortStudent.add(rbSortStudentNameASC);
        buttonGroupSortStudent.add(rbSortStudentNameDESC);

        buttonGroupSearchRegistering.add(rbSearchReByRegisterTime);
        buttonGroupSearchRegistering.add(rbSearchReByStudentName);
    }

    private void addActionListener() {
        btnAddNewSubject.addActionListener(this);
        btnEditSubject.addActionListener(this);
        btnRemoveSubject.addActionListener(this);
        btnRefreshSubject.addActionListener(this);
        btnSearchSubject.addActionListener(this);

        btnAddNewStudent.addActionListener(this);
        btnEditStudent.addActionListener(this);
        btnRefreshStudent.addActionListener(this);
        btnRemoveStudent.addActionListener(this);

        rbSearchSubjectByName.addActionListener(this);
        rbSearchSubjectByNumOfLesson.addActionListener(this);
        rbSortSubjectLessonASC.addActionListener(this);
        rbSortSubjectLessonDESC.addActionListener(this);
        rbSortSubjectNameASC.addActionListener(this);
        rbSortSubjectNameDESC.addActionListener(this);

        rbSortStudentIdASC.addActionListener(this);
        rbSortStudentNameASC.addActionListener(this);
        rbSortStudentNameDESC.addActionListener(this);

        rbSearchStudentId.addActionListener(this);
        rbSearchStudentByName.addActionListener(this);
        rbSearchStudentByMajor.addActionListener(this);
        btnSearchStudent.addActionListener(this);

        btnAddNewRegistering.addActionListener(this);
        btnRefreshRegistering.addActionListener(this);
        btnRemoveRegistering.addActionListener(this);

        comboSortRegistering.addActionListener(this);
        rbSearchReByStudentName.addActionListener(this);
        rbSearchReByRegisterTime.addActionListener(this);
        btnSearchRegistering.addActionListener(this);

        btnCreateCourse.addActionListener(this);
    }

    public void addSubjectCallback(Subject subject) {
        subjects.add(subject);
        showSubject(subject);
        saveData(DataController.SUBJECT);
    }

    public void addStudentCallback(Student student) {
        students.add(student);
        showStudent(student);
        saveData(DataController.STUDENT);
    }

    public boolean addRegisteringCallback(Registering registering) {
        // Check if the number of courses the student has registered for exceeds 7. 
        // If not, register. Then return true.
        var isRegisterable = dataController
                .isRegisterable(registerings, registering.getStudent());
        if (isRegisterable) {
            registerings.add(registering);
            showRegistering(registering);
            saveData(DataController.REGISTERING);
            return true;
        } else {
            return false;
        }
    }

    public void editStudentCallback(Student student) {
        tableModelStudent.removeRow(selectedIndex);
        var format = "dd/MM/yyyy";
        SimpleDateFormat dateFormat = new SimpleDateFormat(format);
        Object[] row = new Object[]{
            student.getStudentId(), student.getFullName(),
            dateFormat.format(student.getDob()), student.getAddress(),
            student.getEmail(), student.getPhoneNumber(),
            student.getStudentClass(), student.getMajor(), student.getSchoolYear()
        };
        tableModelStudent.insertRow(selectedIndex, row);
        students.set(selectedIndex, student);
        saveData(DataController.STUDENT);
        selectedIndex = -1;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        var obj = e.getSource();
        if (obj.equals(btnAddNewSubject)) {
            AddSubjectDialog addSubjectDialog
                    = new AddSubjectDialog(this, rootPaneCheckingEnabled);
            addSubjectDialog.setVisible(true);
        } else if (obj.equals(btnRefreshSubject)) {
            refreshSubjects();
        }
        if (obj.equals(btnRemoveSubject)) {
            removeSubject();
        } else if (obj.equals(btnEditSubject)) {
            editSubject();
        } else if (obj.equals(rbSortSubjectLessonASC)
                || obj.equals(rbSortSubjectLessonDESC)
                || obj.equals(rbSortSubjectNameASC)
                || obj.equals(rbSortSubjectNameDESC)) {
            sortSubjects(obj);
        } else if (obj.equals(btnSearchSubject)) {
            searchSubjects();
        } else if (obj.equals(btnAddNewStudent)) {
            addNewStudent();
        } else if (obj.equals(btnEditStudent)) {
            editStudent();
        } else if (btnRemoveStudent.equals(obj)) {
            removeStudent();
        } else if (obj.equals(btnRefreshStudent)) {
            refreshStudents();
        } else if (obj.equals(rbSortStudentIdASC)
                || obj.equals(rbSortStudentNameASC)
                || obj.equals(rbSortStudentNameDESC)) {
            sortStudents();
        } else if (obj.equals(rbSearchStudentId)
                || obj.equals(rbSearchStudentByName)
                || obj.equals(rbSearchStudentByMajor)) {
            checkSearchField();
        } else if (obj.equals(btnSearchStudent)) {
            searchStudents();
        } else if (obj.equals(btnAddNewRegistering)) {
            addNewRegistering();
        } else if (obj.equals(btnRemoveRegistering)) {
            removeRegistering();
        } else if (obj.equals(comboSortRegistering)) {
            sortRegistering();
        } else if (obj.equals(btnSearchRegistering)) {
            searchRegistering();
        } else if (obj.equals(rbSearchReByRegisterTime)
                || obj.equals(rbSearchReByStudentName)) {
            switchInputState();
        } else if (obj.equals(btnRefreshRegistering)) {
            refreshRegistering();
        } else if (obj.equals(btnCreateCourse)) {
            createCourse();
        }
    }

    private void showSubject(Subject subject) {
        Object[] row = new Object[]{
            subject.getId(), subject.getName(),
            subject.getNumOfLesson(), subject.getKind()
        };
        tableModelSubject.addRow(row);
    }

    private void loadData() {
        subjects = dataController
                .<Subject>readDataFromFile(DataController.SUBJECT_FILE);
        // đọc danh sách sinh viên
        students = dataController.<Student>readDataFromFile(DataController.STUDENT_FILE);
        // đọc danh sách bảng đăng ký
        registerings = dataController.<Registering>readDataFromFile(DataController.REGISTERING_FILE);
        editSubjectId();
    }

    private void showData() {
        showSubjects();
        showStudents();
        showRegisterings();
    }

    private void showSubjects() {
        tableModelSubject.setRowCount(0); // clear data
        for (Subject subject : subjects) {
            showSubject(subject);
        }
    }

    private void saveData(int choice) {
        switch (choice) {
            case DataController.SUBJECT:
                dataController.<Subject>writeToFile(subjects,
                        DataController.SUBJECT_FILE);
                break;
            case DataController.STUDENT:
                dataController.<Student>writeToFile(students,
                        DataController.STUDENT_FILE);
                break;
            case DataController.REGISTERING:
                dataController.<Registering>writeToFile(registerings,
                        DataController.REGISTERING_FILE);
                break;
        }
    }

    private void editSubjectId() {
        int maxId = Subject.getsId();
        for (Subject subject : subjects) {
            if (subject.getId() > maxId) {
                maxId = subject.getId();
            }
        }
        Subject.setsId(maxId + 1);
    }

    private void removeSubject() {
        int selectedIndex = tblSubject.getSelectedRow();
        if (selectedIndex > -1) {
            var msg = "Are you sure you want to delete this record??";
            int confirm = JOptionPane.showConfirmDialog(rootPane, msg);
            if (confirm == JOptionPane.YES_OPTION) { // or OK_OPTION
                subjects.remove(selectedIndex);
                tableModelSubject.removeRow(selectedIndex);
                dataController.<Subject>writeToFile(subjects,
                        DataController.SUBJECT_FILE);
            }
        } else {
            var msg = "Please select 1 record to delete!";
            showDialogMessage(msg);
        }
    }

    private void showDialogMessage(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
    }

    private void editSubject() {
        int selectedIndex = tblSubject.getSelectedRow();
        if (selectedIndex > -1) {
            Subject subject = subjects.get(selectedIndex);
            EditSubjectDialog editSubjectDialog
                    = new EditSubjectDialog(this, true, subject);
            editSubjectDialog.setVisible(true);
        } else {
            var msg = "Please select 1 record to delete!";
            showDialogMessage(msg);
        }
    }

    public void editSubjectCallback(Subject subject) {
        int selectedIndex = tblSubject.getSelectedRow();
        subjects.set(selectedIndex, subject);
        tableModelSubject.removeRow(selectedIndex);
        Object[] row = new Object[]{
            subject.getId(), subject.getName(),
            subject.getNumOfLesson(), subject.getKind()
        };
        tableModelSubject.insertRow(selectedIndex, row);
        saveData(DataController.SUBJECT);
    }

    private void sortSubjects(Object obj) {
        if (obj.equals(rbSortSubjectLessonASC)) {
            dataController.sortSubjectByNumOfLessonASC(subjects);
        } else if (obj.equals(rbSortSubjectLessonDESC)) {
            dataController.sortSubjectByNumOfLessonDESC(subjects);
        } else if (obj.equals(rbSortSubjectNameASC)) {
            dataController.sortSubjectByNameASC(subjects);
        } else if (obj.equals(rbSortSubjectNameDESC)) {
            dataController.sortSubjectByNameDESC(subjects);
        }
        showSubjects();
    }

    private void searchSubjects() {
        if (rbSearchSubjectByName.isSelected()) {
            var key = txtSearchSubjectByName.getText();
            if (key.isEmpty()) {
                var msg = "Please enter the name of the subject "
                        + "you are searching for!";
                showDialogMessage(msg);
            } else {
                var result = dataController.searchSubjectByName(subjects, key);
                subjects.clear();
                subjects.addAll(result);
                checkAndShowSearchResult();
            }
        } else if (rbSearchSubjectByNumOfLesson.isSelected()) {
            var fromValString = txtSearchSubjectLessonFrom.getText();
            var toValString = txtSearchSubjectLessonTo.getText();
            if (!fromValString.isEmpty() && !toValString.isEmpty()) {
                var fromValue = Integer.parseInt(fromValString);
                var toValue = Integer.parseInt(toValString);
                var result = dataController.searchSubjectByLessonRange(subjects,
                        fromValue, toValue);
                subjects.clear();
                subjects.addAll(result);
                checkAndShowSearchResult();
            } else {
                var msg = "Please enter the value of the number"
                        + " section in the subject to be searched!";
                showDialogMessage(msg);
            }
        } else {
            var msg = "Please select search criteria first!";
            showDialogMessage(msg);
        }
    }

    private void checkAndShowSearchResult() {
        if (!subjects.isEmpty()) {
            showSubjects();
            var msg = "Found " + subjects.size() + " results";
            showDialogMessage(msg);
        } else {
            subjects.clear();
            showSubjects();
            var msg = "No results found!";
            showDialogMessage(msg);
        }
    }

    private void refreshSubjects() {
        var text = "";
        txtSearchSubjectByName.setText(text);
        txtSearchSubjectLessonFrom.setText(text);
        txtSearchSubjectLessonTo.setText(text);
        buttonGroupSortSubject.clearSelection();
        buttonGroupSearchSubject.clearSelection();
        subjects.clear();
        subjects.addAll(dataController
                .<Subject>readDataFromFile(DataController.SUBJECT_FILE));
        showSubjects();
    }

    private void addNewStudent() {
        AddStudentDialog addStudentDialog
                = new AddStudentDialog(this, rootPaneCheckingEnabled, students);
        addStudentDialog.setVisible(true);
    }

    private void showStudent(Student student) {
        var format = "dd/MM/yyyy";
        SimpleDateFormat dateFormat = new SimpleDateFormat(format);
        Object[] row = new Object[]{
            student.getStudentId(), student.getFullName(),
            dateFormat.format(student.getDob()), student.getAddress(),
            student.getEmail(), student.getPhoneNumber(),
            student.getStudentClass(), student.getMajor(), student.getSchoolYear()
        };
        tableModelStudent.addRow(row);
    }

    private void showStudents() {
        tableModelStudent.setRowCount(0); // clear data
        for (Student student : students) {
            showStudent(student);
        }
    }

    private void editStudent() {
        selectedIndex = tblStudent.getSelectedRow();
        if (selectedIndex > -1) {
            Student student = students.get(selectedIndex);
            var editStudentDialog = new EditStudentDialog(this, true, student);
            editStudentDialog.setVisible(true);
        } else {
            var msg = "Please select a specific student in the table to edit!";
            showDialogMessage(msg);
        }
    }

    private void removeStudent() {
        int removeIndex = tblStudent.getSelectedRow();
        if (removeIndex >= 0) {
            var msg = "Are you sure you want to delete this record?";
            int retValue = JOptionPane.showConfirmDialog(rootPane, msg);
            if (retValue == JOptionPane.YES_OPTION) {
                tableModelStudent.removeRow(removeIndex);
                students.remove(removeIndex);
                dataController.<Student>writeToFile(students,
                        DataController.STUDENT_FILE);
            }
        } else {
            var msg = "Please select 1 record to delete!";
            showDialogMessage(msg);
        }
    }

    private void refreshStudents() {
        txtSearchStudentById.setEnabled(true);
        txtSearchStudentName.setEnabled(true);
        comboMajor.setEnabled(true);
        buttonGroupSortStudent.clearSelection();
        buttonGroupSearchStudent.clearSelection();
        txtSearchStudentById.setText("");
        txtSearchStudentName.setText("");
        comboMajor.setSelectedIndex(0);
        tableModelStudent.setRowCount(0);
        reloadStudent();
        showStudents();
    }

    private void reloadStudent() {
        students.clear();
        students.addAll(dataController
                .<Student>readDataFromFile(DataController.STUDENT_FILE));
    }

    private void sortStudents() {
        if (rbSortStudentIdASC.isSelected()) {
            dataController.sortStudentByStudentIdASC(students);
        } else if (rbSortStudentNameASC.isSelected()) {
            dataController.sortStudentByNameASC(students);
        } else if (rbSortStudentNameDESC.isSelected()) {
            dataController.sortStudentByNameDESC(students);
        }
        showStudents();
    }

    private void checkSearchField() {
        if (rbSearchStudentId.isSelected()) {
            txtSearchStudentById.setEnabled(true);
            txtSearchStudentName.setEnabled(false);
            comboMajor.setEnabled(false);
        } else if (rbSearchStudentByName.isSelected()) {
            txtSearchStudentById.setEnabled(false);
            txtSearchStudentName.setEnabled(true);
            comboMajor.setEnabled(false);
        } else if (rbSearchStudentByMajor.isSelected()) {
            txtSearchStudentById.setEnabled(false);
            txtSearchStudentName.setEnabled(false);
            comboMajor.setEnabled(true);
        }
    }

    private void searchStudents() {
        reloadStudent();
        if (rbSearchStudentId.isSelected()) {
            var key = txtSearchStudentById.getText();
            if (key.isEmpty()) {
                var msg = "Please enter the student ID you are looking for!";
                showDialogMessage(msg);
            } else {
                var result = dataController.searchStudentById(students, key);
                students.clear();
                students.addAll(result);
                checkAndShowSearchStudentResult();
            }
        } else if (rbSearchStudentByName.isSelected()) {
            var name = txtSearchStudentName.getText();
            if (!name.isEmpty()) {
                var result = dataController.searchStudentByName(students, name);
                students.clear();
                students.addAll(result);
                checkAndShowSearchStudentResult();
            } else {
                var msg = "Please enter the name of the student "
                        + "you are searching for!";
                showDialogMessage(msg);
            }
        } else if (rbSearchStudentByMajor.isSelected()) {
            var major = comboMajor.getSelectedItem().toString();
            if (!major.isEmpty()) {
                var result = dataController.searchStudentByMajor(students, major);
                students.clear();
                students.addAll(result);
                checkAndShowSearchStudentResult();
            } else {
                var msg = "Please select the major is looking for!";
                showDialogMessage(msg);
            }
        } else {
            var msg = "Please select search criteria first!";
            showDialogMessage(msg);
        }
    }

    private void checkAndShowSearchStudentResult() {
        if (!students.isEmpty()) {
            showStudents();
            var msg = "Found " + students.size() + " results";
            showDialogMessage(msg);
        } else {
            students.clear();
            showStudents();
            var msg = "No results found!";
            showDialogMessage(msg);
        }
    }

    private void addNewRegistering() {
        AddRegisterDialog registerDialog = new AddRegisterDialog(this, true,
                students, subjects, registerings);
        registerDialog.setVisible(true);
    }

    private void showRegistering(Registering r) {
        Object[] row = new Object[]{
            r.getStudent().getStudentId(), r.getStudent().getFullName(),
            r.getStudent().getMajor(), r.getSubject().getId(),
            r.getSubject().getName(), simpleDateFormat.format(r.getRegistedDate())
        };
        tableModelRegistering.addRow(row);
    }

    private void showRegisterings() {
        tableModelRegistering.setRowCount(0);
        for (Registering r : registerings) {
            showRegistering(r);
        }
    }

    private void removeRegistering() {
        var index = tblRegistering.getSelectedRow();
        if (index > -1) {
            int retVal = JOptionPane.showConfirmDialog(rootPane,
                    "Are you sure you want to delete this record?");
            if (retVal == JOptionPane.YES_OPTION) {
                tableModelRegistering.removeRow(index);
                registerings.remove(index);
                saveData(DataController.REGISTERING);
            }
        } else {
            var msg = "Please select 1 registration to delete!";
            showDialogMessage(msg);
        }
    }

    private void sortRegistering() {
        int option = comboSortRegistering.getSelectedIndex();
        switch (option) {
            case 0:
                dataController.sortRegisteringByStudentNameAZ(registerings);
                break;
            case 1:
                dataController.sortRegisteringByStudentNameZA(registerings);
                break;
            case 2:
                dataController.sortRegisteringByRegisteringTimeEL(registerings);
                break;
            case 3:
                dataController.sortRegisteringByRegisteringTimeLE(registerings);
                break;
        }
        showRegisterings();
    }

    private void searchRegistering() {
        reloadRegisterings();
        List<Registering> copyList = new ArrayList<>(registerings);
        if (rbSearchReByRegisterTime.isSelected()) {
            var fromStr = txtSearchReByRegisterTimeFrom.getText().trim();
            var toStr = txtSearchReByRegisterTimeTo.getText().trim();
            if (fromStr.isEmpty() || toStr.isEmpty()) {
                var msg = "Please enter the full registration date you are looking for."
                        + "\nFormat: dd/MM/yyyy.";
                showDialogMessage(msg);
            } else {
                var format = "dd/MM/yyyy";
                var dateFormat = new SimpleDateFormat(format);
                try {
                    Date fromDate = dateFormat.parse(fromStr);
                    Date toDate = dateFormat.parse(toStr);
                    registerings.clear();
                    registerings.addAll(dataController.searchReByRegisterTime(
                            copyList, fromDate, toDate));
                    showRegisterings();
                    var msg = "Found " + registerings.size() + " results!";
                    showDialogMessage(msg);
                } catch (ParseException ex) {
                    var msg = "Please enter correct format dd/MM/yyyy.\n"
                            + "Example: 25/01/2025";
                    showDialogMessage(msg);
                }
            }
        } else if (rbSearchReByStudentName.isSelected()) {
            var name = txtSearchReByStudentName.getText();
            if (name.isEmpty()) {
                var msg = "Please enter student name to search!";
                showDialogMessage(msg);
            } else {
                // create new registering after search to display
                registerings.clear();
                registerings.addAll(dataController.searchReByStudentName(
                        copyList, name));
                showRegisterings();
                var msg = "Found " + registerings.size() + " results!";
                showDialogMessage(msg);
            }
        } else {
            var msg = "Please select a search method before searching!";
            showDialogMessage(msg);
        }
    }

    private void reloadRegisterings() {
        registerings.clear();
        registerings.addAll(dataController.<Registering>readDataFromFile(
                DataController.REGISTERING_FILE));
    }

    private void switchInputState() {
        if (rbSearchReByRegisterTime.isSelected()) {
            txtSearchReByRegisterTimeFrom.setEnabled(true);
            txtSearchReByRegisterTimeTo.setEnabled(true);
            txtSearchReByStudentName.setEnabled(false);
        } else if (rbSearchReByStudentName.isSelected()) {
            txtSearchReByStudentName.setEnabled(true);
            txtSearchReByRegisterTimeFrom.setEnabled(false);
            txtSearchReByRegisterTimeTo.setEnabled(false);
        }
    }

    private void refreshRegistering() {
        var emptyText = "";
        txtSearchReByStudentName.setEnabled(true);
        txtSearchReByRegisterTimeFrom.setEnabled(true);
        txtSearchReByRegisterTimeTo.setEnabled(true);
        txtSearchReByStudentName.setText(emptyText);
        txtSearchReByRegisterTimeFrom.setText(emptyText);
        txtSearchReByRegisterTimeTo.setText(emptyText);
        comboSortRegistering.setSelectedIndex(0);
        buttonGroupSearchRegistering.clearSelection();
        reloadRegisterings();
    }

    private void createCourse() {
        dataController.sortRegisteringByRegisteringTimeEL(registerings);
        courses = new ArrayList<>(dataController.createCourse(registerings, subjects));
        showCourses();
    }

    private void showCourses() {
        var emptyStr = "_";
        tableModelCourse.setRowCount(0);
        for (int i = 0; i < courses.size(); i++) {
            var course = courses.get(i);
            for (var r : course.getRegisterings()) {
                Object[] row = new Object[]{
                    course.getName(), r.getStudent().getStudentId(),
                    r.getStudent().getFullName(), r.getStudent().getMajor(),
                    r.getSubject().getId(), r.getSubject().getName(),
                    simpleDateFormat.format(r.getRegistedDate())
                };
                tableModelCourse.addRow(row);
            }
            if (i < courses.size() - 1) {
                var row = new Object[]{emptyStr, emptyStr, emptyStr, emptyStr,
                    emptyStr, emptyStr, emptyStr};
                tableModelCourse.addRow(row);
            }
        }

    }
}
